#ifndef BASICIMPORTER_GLOBAL_H
#define BASICIMPORTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASICIMPORTER_LIBRARY)
#  define BASICIMPORTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASICIMPORTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASICIMPORTER_GLOBAL_H
